### ISSUE TITLE
b58 package missing

### ISSUE THREAD

**Issue by haromz** [btclib-org/btclib#66]
Hello, I installed the package via pip but when I want to use the b58 module like
`from btclib import b58`
I got the following error:
`ImportError: cannot import name 'b58' from 'btclib' (/usr/local/lib/python3.9/site-packages/btclib/__init__.py)`

Checking the packages shows that indeed it is not present
![CleanShot 2022-02-04 at 00 07 10@2x](https://user-images.githubusercontent.com/14028407/152437441-338f1683-17f5-40df-bdd1-db23c4c09139.png)

Any ideas what is wrong or how can I get that module installed?

**Comment by giacomocaironi** [comment]
You are using an outdated version, this is the reason why the b58 file is not present.
We are currently working on a new release, but in the meantime you can install the master branch with this: ``pip install git+https://github.com/btclib-org/btclib/``

**Comment by haromz** [comment]
Strange, because I checked before and I have the latest release as displayed here v2020.12.19
![CleanShot 2022-02-05 at 00 54 49@2x](https://user-images.githubusercontent.com/14028407/152613970-c96a9c74-a9b9-4d41-8c3d-b51876074bcb.png)
Anyhow, will install directly from the repo with the command provided. Thank you!
